version: "3"
services:
  db:
    container_name: {{ cookiecutter.project_slug }}.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB={{ cookiecutter.project_slug }}
    image: postgres:11.1-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    # NOTE: If you need to access the database from an external tool,
    # expose this port and restart the container.
    # ports:
    #   - 5432:5432
    restart: always
  app:
    # Instruct Gunicorn to reload code when it is changed locally.
    command: --reload
    environment:
      - DEBUG=true
      - SECRET_KEY=replace-me
      - DATABASE_URL=psql://postgres:postgres@{{ cookiecutter.project_slug }}.db:5432/{{ cookiecutter.project_slug }}?connect_timeout=60
    links:
      - db
    ports:
      # This port is primarily exposed for debugging. Use the web service's port to properly access the service.
      - 8000:8000
    volumes:
      - .:/app/{{ cookiecutter.project_slug }}:cached
volumes:
  db-data:
